version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
        working_directory: ~/test-kafka
      steps:
        - run:  maven/test # checkout, build, test, and upload test results
